### ISSUE TITLE
0 length array problem

### ISSUE THREAD

**Issue by zkycaesar** [Riscure/java-trsfile#61]
https://github.com/Riscure/java-trsfile/blob/3f9945f92ce75c5fbab8ffeea970f068456a48b7/src/main/java/com/riscure/trs/TraceSet.java#L164

If there is no data in trace, an empty array wiil be put into TraceParameterMap, that will raise a exception.

**Comment by StefanD986** [comment]
Hi @zkycaesar , thanks for reporting.

To clarify, is this what triggers the exception?

```java
TraceSetParameterMap traceSetParameterMap = new TraceSetParameterMap();
traceSetParameterMap.put("LEGACY_DATA", new byte[]{});
```

which then throws this exception:
```
java.lang.IllegalArgumentException: Array length must be positive and non-zero.

	at com.riscure.trs.types.TypedKey.checkLength(TypedKey.java:43)
	at com.riscure.trs.types.ByteArrayTypeKey.createParameter(ByteArrayTypeKey.java:13)
	at com.riscure.trs.types.ByteArrayTypeKey.createParameter(ByteArrayTypeKey.java:6)
	at com.riscure.trs.parameter.traceset.TraceSetParameterMap.put(TraceSetParameterMap.java:98)
	at com.riscure.trs.parameter.traceset.TraceSetParameterMap.put(TraceSetParameterMap.java:149)
	at TestTraceSet.testIssue61(TestTraceSet.java:650)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by zkycaesar** [comment]
> Hi @zkycaesar , thanks for reporting.
> 
> To clarify, is this what triggers the exception?
> 
> ```java
> TraceSetParameterMap traceSetParameterMap = new TraceSetParameterMap();
> traceSetParameterMap.put("LEGACY_DATA", new byte[]{});
> ```
> 
> which then throws this exception:
> 
> ```
> java.lang.IllegalArgumentException: Array length must be positive and non-zero.
> 
> 	at com.riscure.trs.types.TypedKey.checkLength(TypedKey.java:43)
> 	at com.riscure.trs.types.ByteArrayTypeKey.createParameter(ByteArrayTypeKey.java:13)
> 	at com.riscure.trs.types.ByteArrayTypeKey.createParameter(ByteArrayTypeKey.java:6)
> 	at com.riscure.trs.parameter.traceset.TraceSetParameterMap.put(TraceSetParameterMap.java:98)
> 	at com.riscure.trs.parameter.traceset.TraceSetParameterMap.put(TraceSetParameterMap.java:149)
> 	at TestTraceSet.testIssue61(TestTraceSet.java:650)
> [...]
> ```

Yes, that is what I mean.
